### ISSUE TITLE
Incorrect data type of Image.createFrom

### ISSUE THREAD

**Issue by blindpirate** [TomSDEVSN/hetznercloud-java#28]
Got exceptions when creating new servers:

```
java.util.concurrent.ExecutionException: org.springframework.web.client.RestClientException: Error while extracting response for type [class me.tomsdevsn.hetznercloud.objects.response.ServerResponse] and content type [application/json]; nested exception is org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: For input string: "202002E.4202002E4"; nested exception is com.fasterxml.jackson.databind.JsonMappingException: For input string: "202002E.4202002E4" (through reference chain: me.tomsdevsn.hetznercloud.objects.response.ServerResponse["server"]->me.tomsdevsn.hetznercloud.objects.general.Server["image"]->me.tomsdevsn.hetznercloud.objects.general.Image["created"])
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at org.gradle.hetznerautoscaler.TestDistributionAgentPool.startMachines(HetznerAutoscalerApplication.kt:101)
        at org.gradle.hetznerautoscaler.TestDistributionAgentPool.makeSureAgentPoolMatchesWorkload(HetznerAutoscalerApplication.kt:70)
        at org.gradle.hetznerautoscaler.EveryMinuteTask.minuteTask(HetznerAutoscalerApplication.kt:47)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.springframework.web.client.RestClientException: Error while extracting response for type [class me.tomsdevsn.hetznercloud.objects.response.ServerResponse] and content type [application/json]; nested exception is org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: For input string: "202002E.4202002E4"; nested exception is com.fasterxml.jackson.databind.JsonMappingException: For input string: "202002E.4202002E4" (through reference chain: me.tomsdevsn.hetznercloud.objects.response.ServerResponse["server"]->me.tomsdevsn.hetznercloud.objects.general.Server["image"]->me.tomsdevsn.hetznercloud.objects.general.Image["created"])
        at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:120)
        at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:1034)
        at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:1017)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:777)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:710)
        at org.springframework.web.client.RestTemplate.postForEntity(RestTemplate.java:467)
        at me.tomsdevsn.hetznercloud.HetznerCloudAPI.createServer(HetznerCloudAPI.java:113)
        at org.gradle.hetznerautoscaler.DefaultHetznerCloudClient.startServer(HetznerCloudClient.kt:37)
        at org.gradle.hetznerautoscaler.TestDistributionAgentPool$startMachines$$inlined$List$lambda$1.run(HetznerAutoscalerApplication.kt:97)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        ... 3 common frames omitted
```

It seems like that `Image.CreatedFrom.id` should be `String` instead of `Long`: https://github.com/blindpirate/hetznercloud-java/blob/8edd4c91bd01e770875b93e0bedb50a1a14c5a07/src/main/java/me/tomsdevsn/hetznercloud/objects/general/Image.java#L44

**Comment by TomSDEVSN** [comment]
What exactly do you try to get? If I read the exception correctly, you try to get the `created` date and not `createFrom`. The codesnippet where you encounter the issue would be cool.

**Comment by blindpirate** [comment]
Hmmm... I only got that error once. Let's wait for another occurence.
